config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "users#index" # Defines the root path route ("/")

  # The following routes are for the API.
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
  # api/v1/users
  # api/v1/users/:id
  # api/v1/users/:id/posts
  # api/v1/users/:id/posts/:id
  # api/v1/users/:id/posts/:id/comments

  # The following routes are for the web app.
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:new, :create, :destroy]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :comments_count
  after_destroy :comments_count

  # Validation: Comment text must not be blank.
  validates :text, presence: true

  private

  # A method that updates the comments count for a post.
  def comments_count
    post.update(comments_counter: post.comments.count)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def index
    @user = User.find_by(id: params[:user_id])
    user_posts = @user.posts.includes(:comments)
    comments_by_post = user_posts.map { |post| { post_id: post.id, comments: post.comments } }

    render json: { success: true, comments_by_post: }
  end

  def create
    @user = User.find_by(id: params[:user_id])
    post = @user.posts.find_by(id: params[:post_id])

    if post
      comment = post.comments.build(comment_params)
      comment.user = @user

      if comment.save
        render json: { success: true, message: 'Comment created successfully' }, status: :created
      else
        render json: { success: false, message: 'Comment could not be created' }, status: :bad_request
      end
    else
      render json: { success: false, message: 'Post not found' }, status: :not_found
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[new create destroy]
  load_and_authorize_resource only: %i[create destroy]

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post
    if @comment.save
      flash[:notice] = 'Your comment has been added'
      redirect_to user_post_path(@post.author, @post)
    else
      flash.now[:alert] = 'Error while adding your comment'
      render 'new'
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    authorize! :destroy, @comment
    if @comment.destroy
      flash[:notice] = 'The comment was deleted successfully'
    else
      flash.now[:alert] = 'The comment could not be deleted'
    end
    redirect_to user_post_path(@post.author, @post)
  end

  private

  def set_post
    @post = Post.includes(:comments).find_by(id: params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @comment], url: user_post_comments_path(@post.author, @post), local: true) do |form| %>
  <div class="mb-4">
    <%= form.label :text, "Add your comment", class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :text, class: "form-input mt-1 p-2 w-full rounded-md border border-gray-300" %>
  </div>

  <%= button_tag("Submit", class: "bg-green-500 text-white px-4 py-2 rounded-md") %>
<% end %>

app/views/comments/create.html.erb
<h1>New Post</h1>

<%= render partial: "form" , locals: { post: @post, comment: @comment } %>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Here is the form to destroy a given comment</p>
# <p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Here is the form to create a new comment</p>
# <p>Find me in app/views/comments/new.html.erb</p>