config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "users#index" # Defines the root path route ("/")

  # The following routes are for the API.
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
  # api/v1/users
  # api/v1/users/:id
  # api/v1/users/:id/posts
  # api/v1/users/:id/posts/:id
  # api/v1/users/:id/posts/:id/comments

  # The following routes are for the web app.
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:new, :create, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # Validation: Name must not be blank
  validates :name, presence: true

  # Validation: PostsCounter must be an integer greater than or equal to zero
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # A method that returns the 3 most recent posts for a given user.
  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.includes(posts: %i[comments likes]).find_by(id: params[:id])
    @posts = @user.recent_posts
    @post = Post.new
    @like = @posts.present? ? Like.find_by(user: current_user, post: @posts.first) : nil
  end
end

app/views/users/index.html.erb
<div class="container max-w-screen-md m-auto">
  <% @users.each do |user| %>
    <%= link_to user_path(user) do %>
      <%= render partial: "shared/user_card_header", locals: { user: user } %>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container max-w-screen-md m-auto">
  <%= render partial: "shared/user_card_header", locals: { user: @user } %>
  <div class="font-mono shadow-lg border-b-4 border-slate-600 p-4 -mt-8">
    <h2 class="font-bold text-3xl">Bio</h2>
    <p><%= @user.bio %></p>
  </div>

  <!-- Trigger button to open the modal -->
  <%= button_tag("Add a new post", class: "bg-blue-500 text-white px-4 py-2 rounded-md mb-4" , onclick: 'openModal()' ) %>
  
  <!-- Render the modal content using the partial -->
  <%= render partial: "shared/post_creation_modal_form", locals: { user: @user, post: Post.new } %>

  <div class="font-mono border-b-2 mt-14 mb-8">
    <% if @posts.any? %>
      <div class="grid grid-cols-1">
        <% @posts.each do |post| %>
          <%= link_to user_post_path(@user, post) do %>
            <%= render partial: "shared/post_card_preview", locals: { post: post } %>
          <% end %>
        <% end %>
      </div>
      <div class="w-fit mx-auto my-8">
        <%= link_to "See all posts" , user_posts_path(@user),
          class: "px-6 h-12 font-semibold tracking-wider border-2 border-black bg-teal-400 text-black" %>.
      </div>
    <% else %>
      <p><%= @user.name %> hasn't posted anything yet.</p>
    <% end %>
  </div>
</div>