config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "users#index" # Defines the root path route ("/")

  # The following routes are for the API.
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
  # api/v1/users
  # api/v1/users/:id
  # api/v1/users/:id/posts
  # api/v1/users/:id/posts/:id
  # api/v1/users/:id/posts/:id/comments

  # The following routes are for the web app.
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:new, :create, :destroy]
    end
  end
end

app/views/shared/_post_card_preview.html.erb
<%= tag.div id: dom_id(post), class: "card pb-8 mb-8 shadow-sm overflow-wrap relative" do %>
  <h3 class="font-semibold break-all bg-slate-50  text-sky-400 px-1"><span class="text-sky-200">Post: </span><%= post.title %></h3>
  <p class="pl-1 pr-4 break-all"><%= truncate(post.text, length: 100) %></p>
  <div class="flex gap-4 items-center text-[0.7rem] absolute bottom-2 right-8">
    <%= render partial: "shared/post_comments_counter_preview" , locals: { post: post } %>
    <p class="font-mono text-right">Likes: <span class="font-medium text-sky-500 dark:text-sky-400"><%= post.likes_counter %></span></p>
  </div>
<% end %>

app/views/shared/_post_comment_preview.html.erb
<%= tag.div class: "flex gap-4 p-4 mb-4 bg-slate-50" do %>
  <%= link_to user_path(comment.user) do %>
    <h4 class="font-semibold text-sky-500">
      <em><%= comment.user.name %></em>
    </h4>
  <% end %>
  <div class="w-[1px] h-8 bg-slate-200"></div>
  <p><%= comment.text %></p>
<% end %>

app/views/shared/_post_comments_counter_preview.html.erb
<%= tag.div id: dom_id(post) do %>
  <p class="font-mono">Comments: <span class="font-medium text-sky-500 dark:text-sky-400"><%= post.comments_counter %></span></p>
<% end %>

app/views/shared/_post_creation_modal_form.html.erb
<div id="modal" class="z-20">
  <div class="modal-content relative">
    <button type="button" onclick="closeModal()" class="absolute top-0 right-0 mt-4 mr-4 px-2 rounded-full text-2xl text-slate-200 bg-slate-800">X</button>
    <%= render partial: "posts/form", locals: { user: @user, post: Post.new }
    %>
  </div>
</div>

app/views/shared/_post_likes_preview.html.erb
<div class="flex gap-4 items-center my-4">
  <% if @like.present? %>
    <%= form_with(model: [@user, @post, @like], url: user_post_like_path(@user, @post, @like), method: :delete, local: true, class: "like-form w-fit text-lg font-bold text-slate-500 border-2 rounded-full px-2 transition-transform transform hover:scale-105", data: { turbo_frame: "posts" }) do |form| %>
      <%= form.submit 'Dislike', class: "cursor-pointer" %>
    <% end %>
  <% else %>
    <%= form_with(model: [@user, @post, Like.new], url: user_post_likes_path(@user, @post), method: :post, local: true, class: "like-form w-fit text-lg font-bold text-red-700 border-2 rounded-full px-2 transition-transform transform hover:scale-105", data: { turbo_frame: "posts" }) do |form| %>
      <%= form.submit 'Like', class: "cursor-pointer" %>
    <% end %>
  <% end %>
</div>

app/views/shared/_user_card_header.html.erb
<%= tag.figure id: dom_id(user), class: "flex bg-slate-800 shadow-2xl rounded-xl p-8 md:p-0 mb-8 dark:bg-slate-800" do %>
  <% if user.photo? %>
    <%= image_tag user.photo, alt: user.name, class: "w-24 h-24 md:w-48 md:h-auto md:rounded-tl-xl md:rounded-bl-xl rounded-full mx-auto md:-ml-2" , width: "384" , height: "512" %>
  <% else %>
    <!-- Provide a fallback or placeholder image if user.photo is not attached -->
    <%= image_tag "user_fallback_image.jpg" , alt: user.name, class: "w-24 h-24 md:w-48 md:h-auto md:rounded-tl-xl md:rounded-bl-xl rounded-full mx-auto md:-ml-2" , width: "384" , height: "512" %>
  <% end %>
  <div class="w-2/3 pt-6 md:p-8 text-left space-y-4 md:relative">
    <figcaption class="font-medium text-4xl md:text-5xl">
      <div class="text-sky-500 dark:text-sky-400">
        <%= user.name %>
      </div>
    </figcaption>
    <p class="font-mono text-right md:absolute md:bottom-6 md:right-8 text-slate-200 dark:text-slate-200">Number of posts: <span class="font-medium text-sky-500 dark:text-sky-400"><%= user.posts_counter %></span></p>
  </div>
<% end %>