config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "users#index" # Defines the root path route ("/")

  # The following routes are for the API.
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
  # api/v1/users
  # api/v1/users/:id
  # api/v1/users/:id/posts
  # api/v1/users/:id/posts/:id
  # api/v1/users/:id/posts/:id/comments

  # The following routes are for the web app.
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:new, :create, :destroy]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :user_posts_count
  after_destroy :user_posts_count

  # Validation: Title must not be blank and should not exceed 250 characters.
  validates :title, presence: true, length: { maximum: 250 }

  # Validation: comments_counter must be an integer greater than or equal to zero.
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # Validation: likes_counter must be an integer greater than or equal to zero.
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # A method which returns the 5 most recent comments for a given post.
  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  # A method that updates the posts count for a user.
  def user_posts_count
    author.update(posts_counter: author.posts.count)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def index
    @user = User.find_by(id: params[:user_id])
    @posts = @user.posts

    if @posts.present?
      render json: { success: true, user: { user_id: @user.id, name: @user.name, posts: @posts } }
    else
      render json: { success: false, message: 'No posts found' }, status: :not_found
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user, only: %i[index show new create destroy]
  load_and_authorize_resource only: %i[create destroy]

  def index
    @user = User.includes(posts: %i[comments likes]).find_by(id: params[:user_id])
    @post = Post.new
    @posts = @user.posts.includes(:author, :likes, :comments).all.paginate(page: params[:page],
                                                                           per_page: 2).order('created_at DESC')
    @like = @posts.present? ? Like.find_by(user: current_user, post: @posts.first) : nil
  end

  def show
    @post = @user.posts.includes(:comments, :likes).find_by(id: params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:author).order('created_at DESC')
    @like = Like.find_by(user: @user, post: @post)
  end

  def new
    @user = User.find_by(id: params[:user_id])
    @post = @user.posts.new
  end

  def create
    @post = @user.posts.new(post_params)
    @post.author = @user
    if @post.save
      flash[:notice] = 'Post created successfully'
      redirect_to user_post_path(@user, @post)
    else
      flash.now[:alert] = 'Post could not be created'
      render 'new'
    end
  end

  def destroy
    @post = @user.posts.find_by(id: params[:id])
    authorize! :destroy, @post
    if @post.destroy
      flash[:notice] = 'Post deleted successfully'
    else
      flash.now[:alert] = 'Post could not be deleted'
    end
    redirect_to user_posts_path(@user)
  end

  private

  def set_user
    @user = User.includes(posts: %i[comments likes]).find_by(id: params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: [@user, @post], url: user_posts_path(@user), local: true) do |form| %>
  <div class="max-w-md mx-auto bg-white rounded-md overflow-hidden shadow-md p-6">

    <div class="mb-4">
      <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :title, class: "form-input mt-1 p-2 w-full rounded-md border border-gray-300" %>
    </div>

    <div class="mb-4">
      <%= form.label :text, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_area :text, class: "form-input mt-1 p-2 w-full rounded-md border border-gray-300" %>
    </div>

    <%= button_tag("Reset", type: 'reset', class: "bg-blue-500 text-white px-4 py-2 rounded-md mr-2") %>
    <%= form.submit "Create Post", class: "bg-green-500 text-white px-4 py-2 rounded-md" %>
  </div>
<% end %>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Here is the form to destroy a given post</p>
# <p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/index.html.erb
<div class="container max-w-screen-md m-auto">
  <%= render partial: "shared/user_card_header" , locals: { user: @user } %>
  <div class="grid grid-cols-1">
    <!-- Trigger button to open the modal -->
    <%= button_tag("Add a new post", class: "bg-blue-500 text-white px-4 py-2 rounded-md mb-4" , onclick: 'openModal()' ) %>
    <!-- Modal -->
    <%= render partial: "shared/post_creation_modal_form", locals: { user: @user, post: Post.new } %>
    <% @posts.each_with_index do |post, index| %>
      <div class="post-container">
        <%= link_to user_post_path(@user, post) do %>
          <%= render partial: "shared/post_card_preview", locals: { post: post } %>
        <% end %>
        <% if post.comments_counter == 0 %>
          <em class="flex justify-center text-sm text-gray-400 border-[1px] border-gray-100 -mt-8 mb-10 p-4">No comments yet.</em>
        <% else %>
          <div class="border-[1px] border-gray-100 -mt-8 mb-10 p-4">
            <% post.recent_comments.each do |comment| %>
              <%= render partial: "shared/post_comment_preview", locals: { comment: comment } %>
            <% end %>
          </div>
        <% end %>
      </div>
      <% break if index == 1 %> <!-- Break after 2 posts -->
    <% end %>
  </div>
  <div class="flex justify-center mt-4">
    <%= will_paginate @posts, renderer: WillPaginate::ActionView::LinkRenderer, class: "pagination-container px-6 mb-10 font-semibold tracking-wider border-2 border-black bg-teal-400 text-black" %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render partial: "form" , locals: { post: @post, user: @user } %>

app/views/posts/show.html.erb
<div class="container max-w-screen-md m-auto relative">
  <h2 class="font-semibold break-all bg-slate-50  text-sky-400 shadow-md border-b-2 border-slate-600 p-2 pl-4"><%= @post.title %>
    <em class="text-sky-200">by <%= @user.name %></em>
  </h2>
    <% if @post.author == current_user %>
      <% if can? :destroy, Post %>
        <%= button_to "Delete Post" , user_post_path(@user, @post), method: :delete, data: { turbo_confirm: 'Are you sure? this action can not be undone' }, class: "absolute top-0 right-0 font-medium bg-red-600 hover:bg-red-500 text-slate-100 border-[1px] px-2 py-2" %>
      <% end %>
    <% end %>
  <div class="flex gap-4 items-center text-[0.7rem] absolute top-12 right-8">
    <%= render partial: "shared/post_comments_counter_preview" , locals: { post: @post } %>
    <!-- Display the like/dislike button -->
    <p class="font-mono text-right">Likes: <span class="font-medium text-sky-500 dark:text-sky-400"><%= @post.likes_counter %></span></p>
  </div>
  <div class="font-mono border-b-4 border-slate-50 p-4 mt-8">
    <p><%= @post.text %></p>
  </div>
  <% if @post.comments_counter == 0 %>
    <!-- Display the like/dislike button -->
    <%= render partial: "shared/post_likes_preview" , locals: { post: @post, like: @like } %>
    <div class="font-mono border-slate-50 p-4 mt-8">
      <p class="text-sm text-center text-gray-400 -mt-8 mb-10 p-4"><em>No comments yet</em></p>
    </div>
    <div class="border-t-4 border-slate-50 p-4 mt-8">
      <!-- Render the comment form partial -->
      <%= render partial: "comments/form" , locals: { post: @post, comment: Comment.new } %>
    </div>
  <% else %>
    <div>
      <!-- Display the like button and count -->
      <%= render partial: "shared/post_likes_preview" , locals: { post: @post, like: @like } %>
      <h3 class="font-semibold bg-slate-50 text-sky-400 shadow-md border-b-2 border-slate-600 p-2 pl-4 mt-8">Comments</h3>
      <div class="font-mono border-slate-50 p-4 mt-8">
        <% @post.comments.each do |comment| %>
          <div class="relative">
            <%= render partial: "shared/post_comment_preview" , locals: { comment: comment } %>
            <% if can? :destroy, comment %>
              <%= button_to "Delete" , user_post_comment_path(comment.user, comment.post, comment), method: :delete, data: {
                turbo_confirm: 'Are you sure? this action can not be undone' },
                class: "absolute bottom-0 right-0 font-medium bg-red-600 hover:bg-red-500 text-slate-100 border-[1px] px-2 py-2" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="border-t-4 border-slate-50 p-4 mt-8">
      <!-- Render the comment form partial -->
      <%= render partial: "comments/form" , locals: { post: @post, comment: Comment.new } %>
    </div>
  <% end %>
</div>